language: ruby
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
      - "python3-setuptools"
cache: bundler
before_script:
  - bundle install
  - pip3 install --upgrade pip
script:
  - bundle exec jekyll clean && bundle exec jekyll build  --baseurl /cookbook/$TRAVIS_BRANCH
  - chmod 755 $TRAVIS_BUILD_DIR/scripts/validate.py && pip3 install --user -r $TRAVIS_BUILD_DIR/scripts/requirements.txt && $TRAVIS_BUILD_DIR/scripts/validate.sh

after_success:
  - chmod 755 $TRAVIS_BUILD_DIR/scripts/updatePullRequest.sh && export iiifsite=cookbook && $TRAVIS_BUILD_DIR/scripts/updatePullRequest.sh;

deploy:
  provider: s3
  access_key_id:
    secure: hpfSyaRTqWjss62RDzO2IkDMgOSKc4QL69ea79RPlnTVjeMjhOpgrp0FQeN1hPCbM4J//QLKmtZyJ+WjsYImCdkO6S2y8cgsuNbhdT5e/ETOVjmLCDdOTUZoD8B4fsV8ob2t2sqJyoLzveBz+xWDr+pyh3vGDlhxBaOzg2pIZxtuOuJiPXS2bjzzBZeLR5i1sF65xt5WSVpJxw6bBK2TdnX1sxjIimf66j8iu3ImQBR8opwWt6e5IsSkVoLM9DiV3GGaZnRecvBcjBXGeZUBh/DW5a7VGc1CZePOiRdCfjI8Tm8s/nq9XRaiOzyq0ZlSJpUl68++g/gKcs3KndA+kU22CgfZEjTaSxZMNYrVFX6YbCslDqXSnEkd0RZJrPNvaRK8xDOJWRveHws1M5K3CjAX2+dnJ/Xr0FkmG2hZ7AbLAiUqU7S/mga+xPj8pmBUqEZMSOY6zR9nA+t2C4gC1+v4iUjGQPxLKQtIfRPzU2rkTGYFZBQXLNoZQhqP9xf2yhVBsGQdhhgcTcDZqOsMqRfOVUhWwTrr7PKiiXEhiMCrECNFXEsRhvMiyWBvlG2IT5MxTMYntIKKDWnWAPqJ6BJjemHvAaELzMnJhSxy2BdsPlhg6u1aPCbbQAojbwJihRT/ncbpc9mDSEcytuxQayte6FTxMvTLqbiqF8FBBNw=
  secret_access_key:
    secure: wMqhj/RK0Euy7OkttCuTSdcawUUzdKOM5ZoAQHmtqGS2S62BwxncEttgIFdfoWrq3+xNV2RKeUzx14Hy4NXv50XmsH1PXdkYOgA0WX51yLiU7GrOYs3Zo4Ia3Ux5OFOHEUah3XjLzjf68RDNLVsAv+GKJN8mpN1P5KO+0Yuuq89cLyp6CD18z37FQg/EwjWR+Oc3Iw/pEER/Zq4E05/I2FX2no05zOPNM3WnLdfyaGBp6+is/u29SubDi/3fSPuSeJV+QcqyWA9acdCJwqOPhFyWBxhHBekgCuxXV2sTxs71yPEudeIdlfqWbeBOGhlWBZbx5tr+G/A9Qh2jIhoiwivJUqDotBkDmxCM7/wJq3+Kzf+OgZRdIwoFPCWHDR/fg5n7/WlRsSRgWmMN+d5AMVjpKtyA3YO1r+eSKgZrjsooeK9dhPAhA2s/emORnL5M3zv8+fDenswjyhR2MwaRniksiZRNSMqFeCld5w0XbwmFlmIl2uMAs6tvugFo0tGPVdIvRrzp7KX1weQdLGN4GbnyealUW96bMGBu2wmBf/oHBGeG13vSnfdA2DJ3X12Ba93BS0yVKQAMJzVLRLtuy2h1mle/7r9TwpAFtvy9+3x7rxUw5CnGfid5RgxB38avQV8jQRkCYG0GuhXxSWWaJ1uyTumeIjfpyG9uWYGkm/4=
  bucket: preview.iiif.io
  skip_cleanup: true
  detect_encoding: true
  acl: public_read
  region: us-east-1
  local_dir: _site
  upload-dir: cookbook/$TRAVIS_BRANCH
  on:
    all_branches: true

