name: validate

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v5

      - name: Run IIIF validator
        uses: IIIF/presentation-validator@refactor-2026
        with:
          directory: recipe
          version: 3.0