name: validate

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITH: test jekyll_plugins
      SITE_ID:  'cookbook' # which iiif site this is
      URL: 'https://preview.iiif.io'

    steps:
      - name: Check out this repository
        uses: actions/checkout@v6

      # Setup ruby and build site
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: add URL to config
        run: .github/bin/addURL.sh

      - name: Build site
        run: bundle exec rake build:preview

      - name: Run IIIF validator
        uses: IIIF/presentation-validator@main
        with:
          directory: _site/cookbook/HEAD/recipe